# Generated by Django 3.2.5 on 2021-07-11 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35)),
                ('apellido', models.CharField(max_length=35)),
                ('direccion', models.CharField(max_length=40)),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(max_length=35)),
                ('correo', models.CharField(max_length=40)),
            ],
        ),
    ]
