# Generated by Django 3.2.5 on 2021-07-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Clientes', '0003_transacciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacciones',
            name='tranferencia',
            field=models.DecimalField(decimal_places=3, max_digits=50),
        ),
    ]
