# Generated by Django 3.2.5 on 2021-07-11 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_Clientes', '0009_delete_transacciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retiro', models.DecimalField(decimal_places=3, max_digits=50)),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Clientes.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deposito', models.DecimalField(decimal_places=3, max_digits=50)),
                ('fecha_realizacion', models.DateTimeField(auto_now_add=True)),
                ('clientes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_Clientes.clientes')),
            ],
        ),
    ]
